### ISSUE TITLE
The Lerna script cannot find boost when building C++ modules

### ISSUE THREAD

**Issue by wsgeek12** [jpmorganchase/perspective#40]
When I built on MacOS (having installed Boost using brew) everything is fine.

When I followed the directions on Ubuntu, the lerna build script fails whenever a C++ module needs Boost.  I have Boost installed with apt install libboost-dev (so it's in /usr/include).

<code>
Here's  a sample of just one of the many similar errors:
@jpmorganchase/perspective: In file included from /home/dj/usr/src/perspective-clone/packages/perspective/src/cpp/build_filter.cpp:11:
@jpmorganchase/perspective: In file included from /home/dj/usr/src/perspective-clone/packages/perspective/src/include/perspective/build_filter.h:12:
@jpmorganchase/perspective: In file included from /home/dj/usr/src/perspective-clone/packages/perspective/src/include/perspective/filter.h:12:
@jpmorganchase/perspective: /home/dj/usr/src/perspective-clone/packages/perspective/src/include/perspective/base.h:29:10: fatal error: 'boost/unordered_map.hpp' file not found
@jpmorganchase/perspective: #include <boost/unordered_map.hpp>\n         ^~~~~~~~~~~~~~~~~~~~~~~~~

I'm on:
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

$ em++ --version
emcc (Emscripten gcc/clang-like replacement) 1.37.33 ()
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
</code>

**Comment by msturdikova** [comment]
I had the same issue on ubuntu (WSL) and had to copy the boost headers to /src/boost_includes (as expected by CMake - see CMakeLists.txt in perspective package)
Changing the include to point to /usr/include would cause clash with emscripten specific includes.

**Comment by wsgeek12** [comment]
Hmmm ok I see that in the CMakeLists.txt.  I'm not sure people are going to want to create a root level directory called /src/boost_includes and link it to /usr/include (or wherever their boost installation is).  Also, some people might not even have sudo ability to do that.  Am I misunderstanding what you did to solve this?

thx

**Comment by rpasta42** [comment]
I ran into the same issue few weeks ago when attempting to build on Ubuntu 16.04.

I was able to resolve the issue by copying boost folder, but without modifying cmake files.

I used the following command:  `cp -R /usr/include/boost <PERSPECTIVE_ROOT>/src/include/perspective` and the project build successfully.

You might be able to save hard drive space by creating symbolic link without copying full folder, but I haven't tried that approach.

**Comment by wsgeek12** [comment]
Hey that worked -- thank you!

**Comment by tmlbl** [comment]
`cp -r /usr/include/boost ./packages/perspective/src/include/` got it going for me. No way to script this into the build process?

**Comment by texodus** [comment]
There is now a `PSP_DOCKER` environment variable which will run the Emscripten portion of the build with a Docker packaged version of Emscripten:

    PSP_DOCKER=1 npm run build
